model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
      api_key: os.environ/OPENAI_API_KEY

litellm_settings:
  drop_params: true
  set_verbose: false
  callbacks: ["prometheus"]
  service_callback: ["prometheus_system"]

general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
  prometheus_port: 4000

router_settings:
  routing_strategy: least-busy
  redis_host: redis
  redis_port: 6379
  redis_password: os.environ/REDIS_PASSWORD
  cache_responses: true
  cache_kwargs:
    ttl: 600
