name: Docker Image CI

on:
  push:
    branches: ["main"]
    paths:
      - "ai-gateway-stack/**"
      - ".github/workflows/docker-image.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "ai-gateway-stack/**"
      - ".github/workflows/docker-image.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build ./ai-gateway-stack --file ./ai-gateway-stack/Dockerfile --tag ai-gateway-stack-ci:${{ github.sha }}
